import { CivicIssue } from "./types";
import garbageBefore from "./assets/images/garbage_before_1782401711273.jpg";
import garbageAfter from "./assets/images/garbage_after_1782401729523.jpg";
import potholeBefore from "./assets/images/pothole_before_1782401750239.jpg";
import streetlightBefore from "./assets/images/streetlight_before_1782401770449.jpg";

export const SEED_ISSUES: CivicIssue[] = [
  {
    id: "issue-1",
    title: "Garbage Pile near Lanka Market",
    description: "A huge pile of waste and plastic bags is blocking the footpath outside the Lanka Market main gate. It smells bad and attracts street dogs, making it difficult for people to walk safely.",
    category: "waste managemnt",
    locality: "Lanka",
    lat: 25.2798,
    lng: 83.0012,
    severity: "Critical",
    status: "resolved",
    urgency: "Critical",
    urgencyScore: 92,
    priorityScore: 94,
    verificationCount: 52,
    verifications: ["sunflowerr.flowerr25@gmail.com", "voter1@civic.org", "voter2@bhu.ac.in"],
    imageUrl: garbageBefore,
    afterImageUrl: garbageAfter,
    resolvedIn: "3 days",
    aiAnalysis: "This pile blocks the walkway, forcing pedestrians to walk on the busy road. Cleaning this removes a health hazard and restores a clean market entrance.",
    createdAt: "2026-06-22T10:00:00.000Z",
    timeline: [
      {
        status: "reported",
        date: "2026-06-22",
        description: "Report filed by a local resident.",
      },
      {
        status: "verified",
        date: "2026-06-22",
        description: "Verified by 52 neighbor upvotes.",
      },
      {
        status: "resolved",
        date: "2026-06-25",
        description: "Municipal crew cleaned the area, sanitized the ground, and placed planters to prevent dumping.",
      },
    ],
  },
  {
    id: "issue-2",
    title: "Deep Potholes at Assi Crossing",
    description: "Two deep potholes have formed on the road near Assi Crossing. Scooters are swerving dangerously to avoid falling. It is very risky at night or during rain.",
    category: "pothholes",
    locality: "Assi",
    lat: 25.2885,
    lng: 83.0118,
    severity: "High",
    status: "in-progress",
    urgency: "High",
    urgencyScore: 82,
    priorityScore: 79,
    verificationCount: 38,
    verifications: ["assi_comm@gmail.com"],
    imageUrl: potholeBefore,
    aiAnalysis: "A major road hazard for two-wheelers. Fixing this quickly prevents scooter accidents and keeps traffic moving smoothly.",
    createdAt: "2026-06-23T14:30:00.000Z",
    timeline: [
      {
        status: "reported",
        date: "2026-06-23",
        description: "Report filed by a regular commuter.",
      },
      {
        status: "verified",
        date: "2026-06-24",
        description: "Community votes set this issue as high priority.",
      },
      {
        status: "in-progress",
        date: "2026-06-25",
        description: "Road repair team dispatched to fill the potholes with hot asphalt.",
      },
    ],
  },
  {
    id: "issue-3",
    title: "Dark Footpath near BHU Outer Road",
    description: "Three streetlights are broken on the outer wall road of BHU. The footpath is completely dark at night, making it feel unsafe for students and evening walkers.",
    category: "street lights",
    locality: "BHU Gate",
    lat: 25.2748,
    lng: 83.0055,
    severity: "High",
    status: "reported",
    urgency: "Medium",
    urgencyScore: 68,
    priorityScore: 72,
    verificationCount: 19,
    verifications: [],
    imageUrl: streetlightBefore,
    aiAnalysis: "Poor lighting makes walking unsafe at night. Replacing these bulbs ensures a bright, safe path for students and residents.",
    createdAt: "2026-06-24T18:15:00.000Z",
    timeline: [
      {
        status: "reported",
        date: "2026-06-24",
        description: "Report filed by a BHU student.",
      },
      {
        status: "verified",
        date: "2026-06-25",
        description: "Verified by 19 neighbors in the area.",
      },
    ],
  },
  {
    id: "issue-4",
    title: "Major Water Pipeline Burst at Godowlia",
    description: "Clean water is gushing out of a burst pipeline under the street, causing waterlogging and low water pressure in nearby homes.",
    category: "water leakage",
    locality: "Godowlia, Lanka Ward",
    lat: 25.2920,
    lng: 83.0080,
    severity: "Critical",
    status: "reported",
    urgency: "Critical",
    urgencyScore: 94,
    priorityScore: 89,
    verificationCount: 41,
    verifications: [],
    imageUrl: "https://images.unsplash.com/photo-1542013936693-8848e5744a70?auto=format&fit=crop&w=600&q=80",
    aiAnalysis: "Massive freshwater loss. The constant outflow threatens to erode the road foundation and flood low-lying local storefronts.",
    createdAt: "2026-06-25T08:00:00.000Z",
    timeline: [
      {
        status: "reported",
        date: "2026-06-25",
        description: "Report filed by a local business owner.",
      },
    ],
  },
  {
    id: "issue-5",
    title: "Unfinished Footpath & Concrete Blocks near Sigra",
    description: "Concrete blocks and repair gravel left unfinished on the main road walkway for over two weeks, obstructing elderly citizens and causing traffic bottlenecks.",
    category: "roads and infrastructure",
    locality: "Sigra, Lanka Ward",
    lat: 25.3120,
    lng: 82.9940,
    severity: "Medium",
    status: "in-progress",
    urgency: "High",
    urgencyScore: 78,
    priorityScore: 75,
    verificationCount: 15,
    verifications: [],
    imageUrl: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=600&q=80",
    aiAnalysis: "Under construction walkway blocks pedestrian egress. Relocating surplus debris clears the sidewalk and restores smooth vehicle flows.",
    createdAt: "2026-06-24T12:00:00.000Z",
    timeline: [
      {
        status: "reported",
        date: "2026-06-24",
        description: "Report filed by an active citizen.",
      },
      {
        status: "in-progress",
        date: "2026-06-25",
        description: "Inspected by municipal development authority officer.",
      },
    ],
  },
  {
    id: "issue-6",
    title: "Abandonment of Stray Cattle on Sankat Mochan Road",
    description: "Abandonment of cattle on the narrow approach road of Sankat Mochan causes traffic choke points and safety risks during busy hours.",
    category: "roads and infrastructure",
    locality: "Sankat Mochan Road, Assi Ward",
    lat: 25.2818,
    lng: 83.0002,
    severity: "Low",
    status: "reported",
    urgency: "Low",
    urgencyScore: 45,
    priorityScore: 50,
    verificationCount: 8,
    verifications: [],
    imageUrl: "https://images.unsplash.com/photo-1588615419957-bf66d53c6b49?auto=format&fit=crop&w=600&q=80",
    aiAnalysis: "Stray animal grouping blocks the main pedestrian lane. Re-routing animals to a local shelter ensures security for visitors and smooth flow.",
    createdAt: "2026-06-25T16:00:00.000Z",
    timeline: [
      {
        status: "reported",
        date: "2026-06-25",
        description: "Report filed by an Assi Ghat vendor.",
      },
    ],
  },
  {
    id: "issue-7",
    title: "Clogged Drainage System near Assi Ghat",
    description: "Main sewer line blocked causing dirty water backup onto the main entrance walkway near Assi Ghat.",
    category: "water leakage",
    locality: "Assi Ghat, Assi Ward",
    lat: 25.2892,
    lng: 83.0125,
    severity: "High",
    status: "resolved",
    urgency: "High",
    urgencyScore: 85,
    priorityScore: 82,
    verificationCount: 29,
    verifications: [],
    imageUrl: "https://images.unsplash.com/photo-1542013936693-8848e5744a70?auto=format&fit=crop&w=600&q=80",
    afterImageUrl: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=600&q=80",
    resolvedIn: "2 days",
    aiAnalysis: "Blocked main line caused sewage backup. Cleared by municipal high-pressure jetting machine and disinfected the area.",
    createdAt: "2026-06-21T09:00:00.000Z",
    timeline: [
      {
        status: "reported",
        date: "2026-06-21",
        description: "Report filed by Assi Ghat resident association.",
      },
      {
        status: "verified",
        date: "2026-06-21",
        description: "Verified by 29 community votes.",
      },
      {
        status: "resolved",
        date: "2026-06-23",
        description: "Sewer jetting machine cleared the blockage. Path disinfected.",
      }
    ],
  },
  {
    id: "issue-8",
    title: "Pedestrian Crossing Lights Broken at Sigra Chauraha",
    description: "The pedestrian crossing timer light has been broken, making it extremely dangerous for people crossing the busy junction.",
    category: "roads and infrastructure",
    locality: "Sigra Crossroad, BHU Gate Ward",
    lat: 25.3115,
    lng: 82.9935,
    severity: "Medium",
    status: "resolved",
    urgency: "Medium",
    urgencyScore: 70,
    priorityScore: 68,
    verificationCount: 12,
    verifications: [],
    imageUrl: "https://images.unsplash.com/photo-1508962914676-134849a727f0?auto=format&fit=crop&w=600&q=80",
    afterImageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
    resolvedIn: "1 day",
    aiAnalysis: "Walk signals displaying red continuously. Rewired connection box, updated logic board and replaced bulbs.",
    createdAt: "2026-06-20T11:00:00.000Z",
    timeline: [
      {
        status: "reported",
        date: "2026-06-20",
        description: "Report filed by regular commuter.",
      },
      {
        status: "verified",
        date: "2026-06-20",
        description: "Verified by 12 community upvotes.",
      },
      {
        status: "resolved",
        date: "2026-06-21",
        description: "Signals repaired and tested. Operational.",
      }
    ],
  },
];
